[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/MANIFESTUAC:level='requireAdministrator'"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "link-arg=/MANIFESTUAC:level='requireAdministrator'"]
